--- 
framework: jest
postMerge: 
  pattern: 
    - "**/*.test.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "**/*.test.js"
preRun: 
  command:
    - npm i
parallelism: 3
splitmode: file
#testSplit
