--- 
framework: jest
postMerge: 
  pattern: 
    - "**/*.test.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "**/*.test.js"
preRun: 
  command:
    - npm i
    #testpost2
parallelism: 4
splitmode: file
